/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import MODELO.MainFrame;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.dnd.DragGestureEvent;
import javax.swing.BorderFactory;
/**
 *
 * @author darwi
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnpregunt1 = new javax.swing.JButton();
        btnini1 = new javax.swing.JButton();
        btnpregunt2 = new javax.swing.JButton();
        btnpregunt3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setForeground(java.awt.SystemColor.activeCaption);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(49, 49, 49));
        jPanel5.setForeground(new java.awt.Color(102, 102, 102));

        btnpregunt1.setBackground(new java.awt.Color(0, 0, 0));
        btnpregunt1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnpregunt1.setForeground(java.awt.SystemColor.activeCaption);
        btnpregunt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/SETTINGS.png"))); // NOI18N
        btnpregunt1.setText("PREGUNTA 1");
        btnpregunt1.setAutoscrolls(true);
        btnpregunt1.setContentAreaFilled(false);
        btnpregunt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpregunt1.setDoubleBuffered(true);
        btnpregunt1.setFocusCycleRoot(true);
        btnpregunt1.setFocusPainted(false);
        btnpregunt1.setFocusable(false);
        btnpregunt1.setVerifyInputWhenFocusTarget(false);
        btnpregunt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpregunt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpregunt1MouseExited(evt);
            }
        });
        btnpregunt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpregun1ActionPerformed(evt);
            }
        });

        btnini1.setBackground(new java.awt.Color(0, 0, 0));
        btnini1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnini1.setForeground(java.awt.SystemColor.activeCaption);
        btnini1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/CASA.png"))); // NOI18N
        btnini1.setText("  INICIO");
        btnini1.setContentAreaFilled(false);
        btnini1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnini1.setDoubleBuffered(true);
        btnini1.setFocusCycleRoot(true);
        btnini1.setFocusPainted(false);
        btnini1.setFocusable(false);
        btnini1.setVerifyInputWhenFocusTarget(false);
        btnini1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnini1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnini1MouseExited(evt);
            }
        });
        btnini1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnini1btnpregun1ActionPerformed(evt);
            }
        });

        btnpregunt2.setBackground(new java.awt.Color(0, 0, 0));
        btnpregunt2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnpregunt2.setForeground(java.awt.SystemColor.activeCaption);
        btnpregunt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/BUSCA_ORIGINAL.png"))); // NOI18N
        btnpregunt2.setText("PREGUNTA 2");
        btnpregunt2.setAutoscrolls(true);
        btnpregunt2.setContentAreaFilled(false);
        btnpregunt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpregunt2.setDoubleBuffered(true);
        btnpregunt2.setFocusCycleRoot(true);
        btnpregunt2.setFocusPainted(false);
        btnpregunt2.setFocusable(false);
        btnpregunt2.setVerifyInputWhenFocusTarget(false);
        btnpregunt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpregunt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpregunt2MouseExited(evt);
            }
        });
        btnpregunt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpregunt2btnpregun1ActionPerformed(evt);
            }
        });

        btnpregunt3.setBackground(new java.awt.Color(0, 0, 0));
        btnpregunt3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnpregunt3.setForeground(java.awt.SystemColor.activeCaption);
        btnpregunt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/BUSCA_ORIGINAL.png"))); // NOI18N
        btnpregunt3.setText("PREGUNTA 3");
        btnpregunt3.setAutoscrolls(true);
        btnpregunt3.setContentAreaFilled(false);
        btnpregunt3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpregunt3.setDoubleBuffered(true);
        btnpregunt3.setFocusCycleRoot(true);
        btnpregunt3.setFocusPainted(false);
        btnpregunt3.setFocusable(false);
        btnpregunt3.setVerifyInputWhenFocusTarget(false);
        btnpregunt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpregunt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpregunt3MouseExited(evt);
            }
        });
        btnpregunt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpregunt3btnpregun1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnini1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnpregunt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnpregunt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnpregunt3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnini1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnpregunt1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnpregunt2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnpregunt3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 650));

        jPanel6.setBackground(java.awt.SystemColor.inactiveCaption);
        jPanel6.setForeground(new java.awt.Color(102, 102, 102));

        jPanel7.setBackground(new java.awt.Color(49, 49, 49));
        jPanel7.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setText("PRACTICA CALIFICADA_3");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 572, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -10, 800, 650));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpregun1ActionPerformed
            // TODO add your handling code here:
            PREGUNTA_1 p1= new PREGUNTA_1();
             p1.setVisible(true);
        p1.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_btnpregun1ActionPerformed

    private void btnpregunt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpregunt1MouseEntered
        // TODO add your handling code here:
        btnpregunt1.setBorder(
    BorderFactory.createLineBorder(
        new Color(2,0,0),2
    )
);
     btnpregunt1.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btnpregunt1MouseEntered

    private void btnpregunt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpregunt1MouseExited
        // TODO add your handling code here:
    btnpregunt1.setBorder(null);
    }//GEN-LAST:event_btnpregunt1MouseExited

    private void btnini1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnini1MouseEntered
        // TODO add your handling code here:
              btnini1.setBorder(
    BorderFactory.createLineBorder(
        new Color(2,0,0),2
    )
);
     btnini1.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnini1MouseEntered

    private void btnini1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnini1MouseExited
        // TODO add your handling code here:
         btnini1.setBorder(null);
    }//GEN-LAST:event_btnini1MouseExited

    private void btnini1btnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnini1btnpregun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnini1btnpregun1ActionPerformed

    private void btnpregunt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpregunt2MouseEntered
        // TODO add your handling code here:
               btnpregunt2.setBorder(
    BorderFactory.createLineBorder(
        new Color(2,0,0),2
    )
);
     btnpregunt2.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnpregunt2MouseEntered

    private void btnpregunt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpregunt2MouseExited
        // TODO add your handling code here:
           btnpregunt2.setBorder(null);
        
    }//GEN-LAST:event_btnpregunt2MouseExited

    private void btnpregunt2btnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpregunt2btnpregun1ActionPerformed
        // TODO add your handling code here:
        
             PREGUNTA_2 p1= new PREGUNTA_2();
             p1.setVisible(true);
        p1.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_btnpregunt2btnpregun1ActionPerformed

    private void btnpregunt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpregunt3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpregunt3MouseEntered

    private void btnpregunt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpregunt3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpregunt3MouseExited

    private void btnpregunt3btnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpregunt3btnpregun1ActionPerformed
        // TODO add your handling code here:
        MainFrame m = new  MainFrame();
        m.setVisible(true);
    }//GEN-LAST:event_btnpregunt3btnpregun1ActionPerformed

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnini1;
    private javax.swing.JButton btnpregunt1;
    private javax.swing.JButton btnpregunt2;
    private javax.swing.JButton btnpregunt3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
