/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import MODELO.Busqueda_binaria;
import MODELO.Busqueda_lineal;
import MODELO.ListaNumeros;
import MODELO.Numero;
import MODELO.ListaNumeros;
import java.awt.Color;
import javax.swing.BorderFactory;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import MODELO.Txt_utp;
import java.util.ArrayList;
/**
 *
 * @author darwi
 */
public class PREGUNTA_2 extends javax.swing.JFrame {
    private ListaNumeros lista = new ListaNumeros();
private Txt_utp txt = new Txt_utp();
    /**
     * Creates new form PREGUNTA_2
     */
    public PREGUNTA_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        pre1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnmenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnarchiv = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtarchivo = new javax.swing.JTextField();
        rbtlineal = new javax.swing.JRadioButton();
        rbtcomparar = new javax.swing.JRadioButton();
        rbtinaria = new javax.swing.JRadioButton();
        btnbuscar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablalineal = new javax.swing.JTable();
        txtresultado = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablabinaria = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 770));
        setResizable(false);

        pre1.setBackground(java.awt.SystemColor.inactiveCaption);
        pre1.setForeground(new java.awt.Color(102, 102, 102));
        pre1.setPreferredSize(new java.awt.Dimension(945, 670));

        jPanel7.setBackground(new java.awt.Color(49, 49, 49));
        jPanel7.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setText("BÚSQUEDA LINEAL VS BINARIA ");

        btnmenu.setBackground(new java.awt.Color(0, 0, 0));
        btnmenu.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnmenu.setForeground(java.awt.SystemColor.activeCaption);
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MENU_ORIGINAL.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setAutoscrolls(true);
        btnmenu.setContentAreaFilled(false);
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.setDoubleBuffered(true);
        btnmenu.setFocusCycleRoot(true);
        btnmenu.setFocusPainted(false);
        btnmenu.setFocusable(false);
        btnmenu.setVerifyInputWhenFocusTarget(false);
        btnmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenuMouseExited(evt);
            }
        });
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenubtnpregun1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel5.setText("RESULTADO LINEAL");

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel3.setText("ARCHIVO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 111, 34));
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 240, 30));

        btnarchiv.setBackground(new java.awt.Color(0, 0, 0));
        btnarchiv.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnarchiv.setForeground(java.awt.Color.black);
        btnarchiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/CARPETA_1.png"))); // NOI18N
        btnarchiv.setText("CARGAR");
        btnarchiv.setAutoscrolls(true);
        btnarchiv.setContentAreaFilled(false);
        btnarchiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnarchiv.setDoubleBuffered(true);
        btnarchiv.setFocusCycleRoot(true);
        btnarchiv.setFocusPainted(false);
        btnarchiv.setFocusable(false);
        btnarchiv.setVerifyInputWhenFocusTarget(false);
        btnarchiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnarchivMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnarchivMouseExited(evt);
            }
        });
        btnarchiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarchivbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnarchiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 163, 46));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel4.setText("BUSCAR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 34));

        txtarchivo.setEditable(false);
        jPanel1.add(txtarchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 390, 30));

        rbtlineal.setBackground(new java.awt.Color(0, 0, 0));
        rbtlineal.setForeground(java.awt.SystemColor.inactiveCaption);
        rbtlineal.setText("LINEAL");
        rbtlineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtlinealActionPerformed(evt);
            }
        });
        jPanel1.add(rbtlineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 129, -1));

        rbtcomparar.setBackground(new java.awt.Color(0, 0, 0));
        rbtcomparar.setForeground(java.awt.SystemColor.inactiveCaption);
        rbtcomparar.setText("COMPARAR");
        rbtcomparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtcompararActionPerformed(evt);
            }
        });
        jPanel1.add(rbtcomparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 129, -1));

        rbtinaria.setBackground(new java.awt.Color(0, 0, 0));
        rbtinaria.setForeground(java.awt.SystemColor.inactiveCaption);
        rbtinaria.setText("BINARIA");
        rbtinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtinariaActionPerformed(evt);
            }
        });
        jPanel1.add(rbtinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 129, -1));

        btnbuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnbuscar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnbuscar.setForeground(java.awt.Color.black);
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/BUSCA_ORIGINAL.png"))); // NOI18N
        btnbuscar.setText("BUSCAR");
        btnbuscar.setAutoscrolls(true);
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.setDoubleBuffered(true);
        btnbuscar.setFocusCycleRoot(true);
        btnbuscar.setFocusPainted(false);
        btnbuscar.setFocusable(false);
        btnbuscar.setVerifyInputWhenFocusTarget(false);
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbuscarMouseExited(evt);
            }
        });
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 140, 46));

        btnlimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnlimpiar.setForeground(java.awt.Color.black);
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/CLEAN.png"))); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.setAutoscrolls(true);
        btnlimpiar.setContentAreaFilled(false);
        btnlimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlimpiar.setDoubleBuffered(true);
        btnlimpiar.setFocusCycleRoot(true);
        btnlimpiar.setFocusPainted(false);
        btnlimpiar.setFocusable(false);
        btnlimpiar.setVerifyInputWhenFocusTarget(false);
        btnlimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlimpiarMouseExited(evt);
            }
        });
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 163, 46));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel2.setText("PANEL IZQUIERDO");

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        tablalineal.setBackground(java.awt.SystemColor.activeCaptionText);
        tablalineal.setForeground(new java.awt.Color(255, 255, 255));
        tablalineal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "DATOS"
            }
        ));
        jScrollPane2.setViewportView(tablalineal);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        txtresultado.setEditable(false);
        txtresultado.setBackground(java.awt.SystemColor.activeCaption);
        txtresultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtresultado.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);

        tablabinaria.setBackground(java.awt.SystemColor.activeCaptionText);
        tablabinaria.setForeground(new java.awt.Color(255, 255, 255));
        tablabinaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "DATOS"
            }
        ));
        jScrollPane3.setViewportView(tablabinaria);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel6.setText("RESULTADO BINARIA");

        javax.swing.GroupLayout pre1Layout = new javax.swing.GroupLayout(pre1);
        pre1.setLayout(pre1Layout);
        pre1Layout.setHorizontalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pre1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtresultado)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pre1Layout.setVerticalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pre1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pre1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtresultado))
                    .addGroup(pre1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pre1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pre1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnarchivMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnarchivMouseEntered
        // TODO add your handling code here:
        btnarchiv.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnarchiv.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btnarchivMouseEntered

    private void btnarchivMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnarchivMouseExited
        // TODO add your handling code here:
        btnarchiv.setBorder(null);
    }//GEN-LAST:event_btnarchivMouseExited

    private void btnarchivbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarchivbtnpregun1ActionPerformed
        // TODO add your handling code here:
         JFileChooser selector = new JFileChooser();

    int opcion = selector.showOpenDialog(this);

    if (opcion == JFileChooser.APPROVE_OPTION) {

        try {

            File archivo = selector.getSelectedFile();

            txtarchivo.setText(archivo.getAbsolutePath());

            Txt_utp.cargarArchivo(archivo.getAbsolutePath(), lista);

            DefaultTableModel modeloLineal =
                    (DefaultTableModel) tablalineal.getModel();

            DefaultTableModel modeloBinaria =
                    (DefaultTableModel) tablabinaria.getModel();

            modeloLineal.setRowCount(0);
            modeloBinaria.setRowCount(0);

            for (Numero n : lista.getLista()) {

                Object[] fila = {
                    n.getValor()
                };

                modeloLineal.addRow(fila);
                modeloBinaria.addRow(fila);

            }

            txtresultado.setText("");

            JOptionPane.showMessageDialog(
                    this,
                    "Archivo cargado correctamente."
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar el archivo.\n" + e.getMessage()
            );

        }

    }
    }//GEN-LAST:event_btnarchivbtnpregun1ActionPerformed

    private void rbtlinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtlinealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtlinealActionPerformed

    private void rbtcompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtcompararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtcompararActionPerformed

    private void btnbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseEntered
        // TODO add your handling code here:
        btnbuscar.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnbuscar.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnbuscarMouseEntered

    private void btnbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseExited
        // TODO add your handling code here:
        btnbuscar.setBorder(null);
    }//GEN-LAST:event_btnbuscarMouseExited

    private void btnbuscarbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarbtnpregun1ActionPerformed
        // TODO add your handling code here:
         if (lista.getLista().isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Primero cargue un archivo.");

        return;
    }

    if (txtbuscar.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Ingrese el número a buscar.");

        return;
    }
    int numero = Integer.parseInt(txtbuscar.getText());

    if (rbtlineal.isSelected()) {

        Busqueda_lineal lineal = new Busqueda_lineal();

        lineal.buscar(lista.getLista(), numero);

        DefaultTableModel modelo =
                (DefaultTableModel) tablalineal.getModel();

        modelo.setRowCount(0);

        modelo.addRow(new Object[]{
            numero,
            lineal.isEncontrado() ? "SI" : "NO",
            lineal.getPosicion(),
            lineal.getComparaciones(),
            lineal.getTiempo() + " ns"
        });

    }

   

    else if (rbtinaria.isSelected()) {

       Busqueda_binaria binaria = new Busqueda_binaria();

        binaria.buscar(lista.getLista(), numero);

        DefaultTableModel modelo =
                (DefaultTableModel) tablabinaria.getModel();

        modelo.setRowCount(0);

        modelo.addRow(new Object[]{
            numero,
            binaria.isEncontrado() ? "SI" : "NO",
            binaria.getPosicion(),
            binaria.getComparaciones(),
            binaria.getTiempo() + " ns"
        });

    }

    else if (rbtcomparar.isSelected()) {

        Busqueda_lineal lineal = new Busqueda_lineal();

        Busqueda_binaria binaria = new Busqueda_binaria();

        lineal.buscar(lista.getLista(), numero);

        binaria.buscar(lista.getLista(), numero);

        DefaultTableModel modeloL =
                (DefaultTableModel) tablalineal.getModel();

        DefaultTableModel modeloB =
                (DefaultTableModel) tablabinaria.getModel();

        modeloL.setRowCount(0);

        modeloB.setRowCount(0);

        modeloL.addRow(new Object[]{
            numero,
            lineal.isEncontrado() ? "SI" : "NO",
            lineal.getPosicion(),
            lineal.getComparaciones(),
            lineal.getTiempo() + " ns"
        });

        modeloB.addRow(new Object[]{
            numero,
            binaria.isEncontrado() ? "SI" : "NO",
            binaria.getPosicion(),
            binaria.getComparaciones(),
            binaria.getTiempo() + " ns"
        });

    }
    else {

        JOptionPane.showMessageDialog(this,
                "SELECCIONE UN METODO DE BUSQUEDA OÑO.");
    }

    }//GEN-LAST:event_btnbuscarbtnpregun1ActionPerformed

    private void btnlimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimpiarMouseEntered
        // TODO add your handling code here:
        btnlimpiar.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnlimpiar.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnlimpiarMouseEntered

    private void btnlimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimpiarMouseExited
        // TODO add your handling code here:
        btnlimpiar.setBorder(null);

    }//GEN-LAST:event_btnlimpiarMouseExited

    private void btnlimpiarbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarbtnpregun1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnlimpiarbtnpregun1ActionPerformed

    private void rbtinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtinariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtinariaActionPerformed

    private void btnmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseEntered
        // TODO add your handling code here:
        btnmenu.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnmenu.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnmenuMouseEntered

    private void btnmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseExited
        // TODO add your handling code here:
        btnmenu.setBorder(null);
    }//GEN-LAST:event_btnmenuMouseExited

    private void btnmenubtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenubtnpregun1ActionPerformed
        // TODO add your handling code here:
        MENU m = new MENU();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnmenubtnpregun1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnarchiv;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pre1;
    private javax.swing.JRadioButton rbtcomparar;
    private javax.swing.JRadioButton rbtinaria;
    private javax.swing.JRadioButton rbtlineal;
    private javax.swing.JTable tablabinaria;
    private javax.swing.JTable tablalineal;
    private javax.swing.JTextField txtarchivo;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtresultado;
    // End of variables declaration//GEN-END:variables
}
