/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author darwi
 */
public class PREGUNTA_2 extends javax.swing.JFrame {

    /**
     * Creates new form PREGUNTA_2
     */
    public PREGUNTA_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        pre1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnmenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnarchiv = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        rbtshell = new javax.swing.JRadioButton();
        rtbquic = new javax.swing.JRadioButton();
        rtbquic1 = new javax.swing.JRadioButton();
        btnorden = new javax.swing.JButton();
        btnlimp1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladerecho = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabladerecho1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 770));
        setResizable(false);

        pre1.setBackground(java.awt.SystemColor.inactiveCaption);
        pre1.setForeground(new java.awt.Color(102, 102, 102));
        pre1.setPreferredSize(new java.awt.Dimension(945, 670));

        jPanel7.setBackground(new java.awt.Color(49, 49, 49));
        jPanel7.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setText("BÚSQUEDA LINEAL VS BINARIA ");

        btnmenu.setBackground(new java.awt.Color(0, 0, 0));
        btnmenu.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnmenu.setForeground(java.awt.SystemColor.activeCaption);
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MENU_ORIGINAL.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setAutoscrolls(true);
        btnmenu.setContentAreaFilled(false);
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.setDoubleBuffered(true);
        btnmenu.setFocusCycleRoot(true);
        btnmenu.setFocusPainted(false);
        btnmenu.setFocusable(false);
        btnmenu.setVerifyInputWhenFocusTarget(false);
        btnmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenuMouseExited(evt);
            }
        });
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenubtnpregun1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel5.setText("RESULTADO LINEAL");

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel3.setText("ARCHIVO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 111, 34));

        jTextField1.setEditable(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 240, 30));

        btnarchiv.setBackground(new java.awt.Color(0, 0, 0));
        btnarchiv.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnarchiv.setForeground(java.awt.Color.black);
        btnarchiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/CARPETA_1.png"))); // NOI18N
        btnarchiv.setText("CARGAR");
        btnarchiv.setAutoscrolls(true);
        btnarchiv.setContentAreaFilled(false);
        btnarchiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnarchiv.setDoubleBuffered(true);
        btnarchiv.setFocusCycleRoot(true);
        btnarchiv.setFocusPainted(false);
        btnarchiv.setFocusable(false);
        btnarchiv.setVerifyInputWhenFocusTarget(false);
        btnarchiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnarchivMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnarchivMouseExited(evt);
            }
        });
        btnarchiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarchivbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnarchiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 163, 46));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel4.setText("BUSCAR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 34));

        jTextField2.setEditable(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 390, 30));

        rbtshell.setBackground(new java.awt.Color(0, 0, 0));
        rbtshell.setForeground(java.awt.SystemColor.inactiveCaption);
        rbtshell.setText("LINEAL");
        rbtshell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtshellActionPerformed(evt);
            }
        });
        jPanel1.add(rbtshell, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 129, -1));

        rtbquic.setBackground(new java.awt.Color(0, 0, 0));
        rtbquic.setForeground(java.awt.SystemColor.inactiveCaption);
        rtbquic.setText("COMPARAR");
        rtbquic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtbquicActionPerformed(evt);
            }
        });
        jPanel1.add(rtbquic, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 129, -1));

        rtbquic1.setBackground(new java.awt.Color(0, 0, 0));
        rtbquic1.setForeground(java.awt.SystemColor.inactiveCaption);
        rtbquic1.setText("BINARIA");
        rtbquic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtbquic1ActionPerformed(evt);
            }
        });
        jPanel1.add(rtbquic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 129, -1));

        btnorden.setBackground(new java.awt.Color(0, 0, 0));
        btnorden.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnorden.setForeground(java.awt.Color.black);
        btnorden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/BUSCA_ORIGINAL.png"))); // NOI18N
        btnorden.setText("BUSCAR");
        btnorden.setAutoscrolls(true);
        btnorden.setContentAreaFilled(false);
        btnorden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnorden.setDoubleBuffered(true);
        btnorden.setFocusCycleRoot(true);
        btnorden.setFocusPainted(false);
        btnorden.setFocusable(false);
        btnorden.setVerifyInputWhenFocusTarget(false);
        btnorden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnordenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnordenMouseExited(evt);
            }
        });
        btnorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenbtnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 140, 46));

        btnlimp1.setBackground(new java.awt.Color(0, 0, 0));
        btnlimp1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnlimp1.setForeground(java.awt.Color.black);
        btnlimp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/CLEAN.png"))); // NOI18N
        btnlimp1.setText("LIMPIAR");
        btnlimp1.setAutoscrolls(true);
        btnlimp1.setContentAreaFilled(false);
        btnlimp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlimp1.setDoubleBuffered(true);
        btnlimp1.setFocusCycleRoot(true);
        btnlimp1.setFocusPainted(false);
        btnlimp1.setFocusable(false);
        btnlimp1.setVerifyInputWhenFocusTarget(false);
        btnlimp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlimp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlimp1MouseExited(evt);
            }
        });
        btnlimp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimp1btnpregun1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 163, 46));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel2.setText("PANEL IZQUIERDO");

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        tabladerecho.setBackground(java.awt.SystemColor.activeCaptionText);
        tabladerecho.setForeground(new java.awt.Color(255, 255, 255));
        tabladerecho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "DATOS"
            }
        ));
        jScrollPane2.setViewportView(tabladerecho);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTextField3.setEditable(false);
        jTextField3.setBackground(java.awt.SystemColor.activeCaption);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);

        tabladerecho1.setBackground(java.awt.SystemColor.activeCaptionText);
        tabladerecho1.setForeground(new java.awt.Color(255, 255, 255));
        tabladerecho1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "DATOS"
            }
        ));
        jScrollPane3.setViewportView(tabladerecho1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel6.setText("RESULTADO BINARIA");

        javax.swing.GroupLayout pre1Layout = new javax.swing.GroupLayout(pre1);
        pre1.setLayout(pre1Layout);
        pre1Layout.setHorizontalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pre1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pre1Layout.setVerticalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pre1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pre1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3))
                    .addGroup(pre1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pre1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pre1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnarchivMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnarchivMouseEntered
        // TODO add your handling code here:
        btnarchiv.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnarchiv.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btnarchivMouseEntered

    private void btnarchivMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnarchivMouseExited
        // TODO add your handling code here:
        btnarchiv.setBorder(null);
    }//GEN-LAST:event_btnarchivMouseExited

    private void btnarchivbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarchivbtnpregun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnarchivbtnpregun1ActionPerformed

    private void rbtshellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtshellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtshellActionPerformed

    private void rtbquicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtbquicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtbquicActionPerformed

    private void btnordenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnordenMouseEntered
        // TODO add your handling code here:
        btnorden.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnorden.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnordenMouseEntered

    private void btnordenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnordenMouseExited
        // TODO add your handling code here:
        btnorden.setBorder(null);
    }//GEN-LAST:event_btnordenMouseExited

    private void btnordenbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenbtnpregun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnordenbtnpregun1ActionPerformed

    private void btnlimp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimp1MouseEntered
        // TODO add your handling code here:
        btnlimp1.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnlimp1.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnlimp1MouseEntered

    private void btnlimp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimp1MouseExited
        // TODO add your handling code here:
        btnlimp1.setBorder(null);

    }//GEN-LAST:event_btnlimp1MouseExited

    private void btnlimp1btnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimp1btnpregun1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnlimp1btnpregun1ActionPerformed

    private void rtbquic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtbquic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtbquic1ActionPerformed

    private void btnmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseEntered
        // TODO add your handling code here:
        btnmenu.setBorder(
            BorderFactory.createLineBorder(
                new Color(0,0,0),2
            )
        );
        btnmenu.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnmenuMouseEntered

    private void btnmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseExited
        // TODO add your handling code here:
        btnmenu.setBorder(null);
    }//GEN-LAST:event_btnmenuMouseExited

    private void btnmenubtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenubtnpregun1ActionPerformed
        // TODO add your handling code here:
        MENU m = new MENU();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnmenubtnpregun1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnarchiv;
    private javax.swing.JButton btnlimp1;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnorden;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel pre1;
    private javax.swing.JRadioButton rbtshell;
    private javax.swing.JRadioButton rtbquic;
    private javax.swing.JRadioButton rtbquic1;
    private javax.swing.JTable tabladerecho;
    private javax.swing.JTable tabladerecho1;
    // End of variables declaration//GEN-END:variables
}
