/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author darwi
 */
public class PREGUNTA_1 extends javax.swing.JFrame {

    /**
     * Creates new form PREGUNTA_1
     */
    public PREGUNTA_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        pre1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnarchiv = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rbtshell = new javax.swing.JRadioButton();
        rtbquic = new javax.swing.JRadioButton();
        btnorden = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnlimp1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaordenado = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaoriginal = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnmenu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pre1.setBackground(java.awt.SystemColor.inactiveCaption);
        pre1.setForeground(new java.awt.Color(102, 102, 102));

        jPanel7.setBackground(new java.awt.Color(49, 49, 49));
        jPanel7.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setText("  ORDENACIÓN   ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTextField1.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel2.setText("DATOS ORDENADOS");

        btnarchiv.setBackground(new java.awt.Color(0, 0, 0));
        btnarchiv.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnarchiv.setForeground(java.awt.Color.black);
        btnarchiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/CARPETA_1.png"))); // NOI18N
        btnarchiv.setText("CARGAR");
        btnarchiv.setAutoscrolls(true);
        btnarchiv.setContentAreaFilled(false);
        btnarchiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnarchiv.setDoubleBuffered(true);
        btnarchiv.setFocusCycleRoot(true);
        btnarchiv.setFocusPainted(false);
        btnarchiv.setFocusable(false);
        btnarchiv.setVerifyInputWhenFocusTarget(false);
        btnarchiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnarchivMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnarchivMouseExited(evt);
            }
        });
        btnarchiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarchivbtnpregun1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel3.setText("ARCHIVO:");

        rbtshell.setBackground(new java.awt.Color(0, 0, 0));
        rbtshell.setForeground(java.awt.SystemColor.inactiveCaption);
        rbtshell.setText("SHELL");
        rbtshell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtshellActionPerformed(evt);
            }
        });

        rtbquic.setBackground(new java.awt.Color(0, 0, 0));
        rtbquic.setForeground(java.awt.SystemColor.inactiveCaption);
        rtbquic.setText("QUICK SORT");
        rtbquic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtbquicActionPerformed(evt);
            }
        });

        btnorden.setBackground(new java.awt.Color(0, 0, 0));
        btnorden.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnorden.setForeground(java.awt.Color.black);
        btnorden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ORDENARRRR.png"))); // NOI18N
        btnorden.setText("ORDENAR");
        btnorden.setAutoscrolls(true);
        btnorden.setContentAreaFilled(false);
        btnorden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnorden.setDoubleBuffered(true);
        btnorden.setFocusCycleRoot(true);
        btnorden.setFocusPainted(false);
        btnorden.setFocusable(false);
        btnorden.setVerifyInputWhenFocusTarget(false);
        btnorden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnordenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnordenMouseExited(evt);
            }
        });
        btnorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenbtnpregun1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel4.setText("ALGORITMO");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel5.setText("DATOS ORIGINALES");

        btnlimp1.setBackground(new java.awt.Color(0, 0, 0));
        btnlimp1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnlimp1.setForeground(java.awt.Color.black);
        btnlimp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/CLEAN.png"))); // NOI18N
        btnlimp1.setText("LIMPIAR");
        btnlimp1.setAutoscrolls(true);
        btnlimp1.setContentAreaFilled(false);
        btnlimp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlimp1.setDoubleBuffered(true);
        btnlimp1.setFocusCycleRoot(true);
        btnlimp1.setFocusPainted(false);
        btnlimp1.setFocusable(false);
        btnlimp1.setVerifyInputWhenFocusTarget(false);
        btnlimp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlimp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlimp1MouseExited(evt);
            }
        });
        btnlimp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimp1btnpregun1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pre1Layout = new javax.swing.GroupLayout(pre1);
        pre1.setLayout(pre1Layout);
        pre1Layout.setHorizontalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pre1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pre1Layout.createSequentialGroup()
                        .addGap(0, 106, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(307, 307, 307)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(pre1Layout.createSequentialGroup()
                        .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pre1Layout.createSequentialGroup()
                                .addComponent(rbtshell, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rtbquic, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1))
                        .addGap(28, 28, 28)
                        .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnlimp1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnorden, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnarchiv, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))))
        );
        pre1Layout.setVerticalGroup(
            pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pre1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnarchiv, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtshell)
                    .addComponent(rtbquic)
                    .addComponent(btnorden, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(btnlimp1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        tablaordenado.setBackground(new java.awt.Color(0, 0, 0));
        tablaordenado.setForeground(new java.awt.Color(255, 255, 255));
        tablaordenado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "DATOS"
            }
        ));
        jScrollPane1.setViewportView(tablaordenado);

        tablaoriginal.setBackground(new java.awt.Color(0, 0, 0));
        tablaoriginal.setForeground(new java.awt.Color(255, 255, 255));
        tablaoriginal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "DATOS"
            }
        ));
        jScrollPane2.setViewportView(tablaoriginal);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(java.awt.SystemColor.activeCaption);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        btnmenu.setBackground(new java.awt.Color(0, 0, 0));
        btnmenu.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnmenu.setForeground(java.awt.SystemColor.activeCaption);
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/MENU_ORIGINAL.png"))); // NOI18N
        btnmenu.setText("MENU");
        btnmenu.setAutoscrolls(true);
        btnmenu.setContentAreaFilled(false);
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.setDoubleBuffered(true);
        btnmenu.setFocusCycleRoot(true);
        btnmenu.setFocusPainted(false);
        btnmenu.setFocusable(false);
        btnmenu.setVerifyInputWhenFocusTarget(false);
        btnmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenuMouseExited(evt);
            }
        });
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenubtnpregun1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel6.setText("RESULTADOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnarchivMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnarchivMouseEntered
        // TODO add your handling code here:
             btnarchiv.setBorder(
    BorderFactory.createLineBorder(
        new Color(0,0,0),2
    )
);
     btnarchiv.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btnarchivMouseEntered

    private void btnarchivMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnarchivMouseExited
        // TODO add your handling code here:
          btnarchiv.setBorder(null);
    }//GEN-LAST:event_btnarchivMouseExited

    private void btnarchivbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarchivbtnpregun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnarchivbtnpregun1ActionPerformed

    private void rbtshellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtshellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtshellActionPerformed

    private void rtbquicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtbquicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtbquicActionPerformed

    private void btnmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseEntered
        // TODO add your handling code here:
             btnmenu.setBorder(
    BorderFactory.createLineBorder(
        new Color(0,0,0),2
    )
);
     btnmenu.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnmenuMouseEntered

    private void btnmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseExited
        // TODO add your handling code here:
          btnmenu.setBorder(null);
    }//GEN-LAST:event_btnmenuMouseExited

    private void btnmenubtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenubtnpregun1ActionPerformed
        // TODO add your handling code here:
          MENU m = new MENU();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnmenubtnpregun1ActionPerformed

    private void btnordenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnordenMouseEntered
        // TODO add your handling code here:
             btnorden.setBorder(
    BorderFactory.createLineBorder(
        new Color(0,0,0),2
    )
);
     btnorden.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnordenMouseEntered

    private void btnordenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnordenMouseExited
        // TODO add your handling code here:
          btnorden.setBorder(null);
    }//GEN-LAST:event_btnordenMouseExited

    private void btnordenbtnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenbtnpregun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnordenbtnpregun1ActionPerformed

    private void btnlimp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimp1MouseEntered
        // TODO add your handling code here:
         btnlimp1.setBorder(
    BorderFactory.createLineBorder(
        new Color(0,0,0),2
    )
);
     btnlimp1.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_btnlimp1MouseEntered

    private void btnlimp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimp1MouseExited
        // TODO add your handling code here:
         btnlimp1.setBorder(null);
        
    }//GEN-LAST:event_btnlimp1MouseExited

    private void btnlimp1btnpregun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimp1btnpregun1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnlimp1btnpregun1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnarchiv;
    private javax.swing.JButton btnlimp1;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnorden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pre1;
    private javax.swing.JRadioButton rbtshell;
    private javax.swing.JRadioButton rtbquic;
    private javax.swing.JTable tablaordenado;
    private javax.swing.JTable tablaoriginal;
    // End of variables declaration//GEN-END:variables
}
